### ISSUE TITLE
How to split polygon with a line?

### ISSUE THREAD

**Issue by ganisback** [GEOSwift/GEOSwift#139]
Hi All, is there any way to split a polygon? very appreciated if have an example.

**Comment by piyushvaish** [comment]
Any updates on the same?

**Comment by macdrevx** [comment]
I haven't used it personally, but a quick web search seems to suggest that the [geos polygonize functionality](https://git.osgeo.org/gitea/geos/geos/src/tag/3.7.1/capi/geos_c.h.in#L609) might be able to solve this for you. Seems like the workflow for your specific case (polygon + line) might be something like:

1. get boundary of polygon
2. union the boundary and your line
3. polygonize the result of the union to get split polygons

GEOSwift 5 has support for 1 (boundary) and 2 (union) but not 3 (polygonize). Let's mark this as a feature request and get it added to a future version of the library.

In the meantime, you might be able to accomplish what you want by using geos directly instead of GEOSwift. If you do, please share anything you learn to help us add support for polygonize to GEOSwift.

**Comment by macdrevx** [comment]
@ganisback @piyushvaish if you still need this feature, I've just pushed a [branch](https://github.com/GEOSwift/GEOSwift/tree/polygonize) that exposes polygonize and enables this use case. Here's an example of how you can do it:

```
let polygon = try! GEOSwift.Polygon(exterior: GEOSwift.Polygon.LinearRing(points: [
    Point(x: 0, y: 0),
    Point(x: 1, y: 0),
    Point(x: 1, y: 1),
    Point(x: 0, y: 1),
    Point(x: 0, y: 0)]))
let line = try! LineString(points: [
    Point(x: -1, y: 2),
    Point(x: 2, y: -1)])

print(try! polygon.boundary().union(with: line).polygonize())
```

which results in

```
GeometryCollection(geometries: [
  Polygon(exterior: Polygon.LinearRing(
    points: [
      Point(x: 1.0, y: 0.0),
      Point(x: 0.0, y: 0.0),
      Point(x: 0.0, y: 1.0),
      Point(x: 1.0, y: 0.0)]),
    holes: [])),
  Polygon(exterior: Polygon.LinearRing(
    points: [
      Point(x: 0.0, y: 1.0),
      Point(x: 1.0, y: 1.0),
      Point(x: 1.0, y: 0.0),
      Point(x: 0.0, y: 1.0)]),
    holes: []))
])
```

(cleaned up for readability).

If you have a chance, give it a try and let me know how it works for your use case.

**Comment by macdrevx** [comment]
This is now available in v6.2.0. Enjoy!

**Comment by valvarezf** [comment]
I know this is very old, but I 'm using the last version of gdal using c++ and I have the same problem. I tried several methods:
.- OverlayNG::overlay DIFFERENCE
.- intersection and then add intersection and polygon to a polygonizer
.- symdifference / difference
.- intersection and then difference / symdifference
.- intersection and then EnhancedPrecisionOp::difference / EnhancedPrecisionOp::symdifference
.- intersection and then add intersection and polygon to a geomcollection and then use polygonizer
Two or three aditional methods I can't remember know.

Can someone help me?

**Comment by nanang-rafsanjani-datamine** [comment]
Hi @scottrhoyt, thanks for your reply.

The error doesn’t seem to be caused by a forced `try!`, as it still crashes even when using `try?`. Unfortunately, there aren’t any meaningful logs, but I can share this debug screenshot from when the crash occurred.

<img width="1242" height="1152" alt="Image" src="https://github.com/user-attachments/assets/ab44b81b-d962-4682-a725-733b281c6b6c" />

**Comment by macdrevx** [comment]
> Hi [@scottrhoyt](https://github.com/scottrhoyt), thanks for your reply.
> 
> The error doesn’t seem to be caused by a forced `try!`, as it still crashes even when using `try?`. Unfortunately, there aren’t any meaningful logs, but I can share this debug screenshot from when the crash occurred.

I wasn't able to repro this locally using GEOSwift 11.2.0 and geos 9.0.0. Which versions are you using? Could you share a sample project that repros the problem?
